GET http://localhost:8080/worlds


###
POST http://localhost:8080/worlds
Content-Type: application/json

{
  "name" : "Teaeestttt",
  "img" : "Claymore.jpg",
  "personDtos" : null
}


###
PUT http://localhost:8080/worlds/14
Content-Type: application/json

{
"name" : "TestUpdate",
"img" : "Claymore.jpg",
"personDtos" : null
}


###
DELETE http://localhost:8080/worlds/12

